services:
  messenger:
    container_name: messenger
    build:
      context: ./messenger
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./messenger/configs/local.env
    volumes:
      - ./messenger/configs:/app/configs
    command: ["-config=configs/config.yaml"]
    depends_on:
      redis:
        condition: service_healthy
      # зависимости во время локальной разработки
      postgresql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/ping"]
      interval: 10s                                                                                                                                       
      timeout: 5s
      retries: 5                                                                                                                                          
      start_period: 5s
    networks:
      - realtime

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - realtime

  redis:
    image: redis:8.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - ./messenger/configs/local.env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - realtime

  # postgresql для локальной разработки
  postgresql:
    image: postgres:18-alpine
    container_name: postgresql
    volumes:
      - messenger_db:/var/lib/postgresql
    env_file:
      - ./messenger/configs/local.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - realtime

  # миграции для локальной разработки
  migrations:
    image: migrate/migrate
    container_name: migrations
    volumes:
      - ./messenger/migrations:/migrations
    env_file:
      - ./messenger/configs/local.env
    entrypoint: ["sh", "-c"]
    command: >
      "migrate -path=/migrations/ 
      -database=postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@$${POSTGRES_HOST}:$${POSTGRES_PORT}/$${POSTGRES_DB}?sslmode=$${POSTGRES_SSLMODE} 
      up"
    # down/force НОМЕР_МИГРАЦИИ
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - realtime

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    depends_on:                                                                                                                                             
      messenger:    
        condition: service_healthy  
    networks:
      - realtime

# локальная база данных
volumes:
  messenger_db:

networks:
  realtime:
    driver: bridge